# Usando a imagem oficial do PostgreSQL
FROM postgres:15.2

# Definindo as variáveis de ambiente necessárias
ENV POSTGRES_DB=desafio
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Expondo a porta padrão do PostgreSQL
EXPOSE 5432

# Comando de inicialização
CMD ["postgres"]
